# Generated by Django 5.2.8 on 2025-11-13 02:31

import datetime
import django.db.models.deletion
import requests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of category', max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of design', max_length=200, verbose_name='name')),
                ('summary', models.TextField(help_text="design's summary", max_length=500, verbose_name='summary')),
                ('image', models.ImageField(blank=True, help_text="design's image", null=True, upload_to='', validators=[requests.validators.validate_image_size, requests.validators.validate_image_format], verbose_name='image')),
                ('creation_date', models.DateField(default=datetime.datetime(2025, 11, 13, 9, 31, 38, 522991), help_text="date and time of design's creation", verbose_name='creation date')),
                ('status', models.CharField(choices=[('n', 'New'), ('a', 'Accepted'), ('c', 'Complete')], default='n', help_text='request status', max_length=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.categories')),
            ],
        ),
    ]
