# Generated by Django 5.2.8 on 2025-11-13 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 5, 17, 25, 71162, tzinfo=datetime.timezone.utc), help_text="date and time of design's creation", verbose_name='creation date'),
        ),
    ]
