# Generated by Django 5.2.8 on 2025-11-13 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_rename_categories_category_request_delete_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 13, 40, 0, 31554), help_text="date and time of design's creation", verbose_name='creation date'),
        ),
    ]
