# Generated by Django 5.2.8 on 2025-11-14 02:42

import datetime
import requests.utilities
import requests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_request_creation_date_alter_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 42, 34, 983221), help_text="date and time of design's creation", verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, help_text="design's image", null=True, upload_to=requests.utilities.rename_image, validators=[requests.validators.validate_image_size, requests.validators.validate_image_format], verbose_name='image'),
        ),
    ]
