# Generated by Django 5.2.8 on 2025-11-18 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 18, 8, 46, 37, 600124), help_text='Дата и время создания заявки', verbose_name='Дата создания'),
        ),
    ]
