# Generated by Django 5.2.8 on 2025-11-17 04:31

import datetime
import requests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absuser',
            name='FIO',
            field=models.CharField(max_length=255, validators=[requests.validators.validate_FIO], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='absuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 17, 11, 31, 32, 606631), help_text="date and time of design's creation", verbose_name='creation date'),
        ),
    ]
