# Generated by Django 5.2.8 on 2025-11-17 04:42

import datetime
import requests.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_absuser_fio_alter_absuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absuser',
            name='FIO',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 17, 11, 42, 25, 708216), help_text="date and time of design's creation", verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, help_text="design's image", null=True, upload_to=requests.utilities.rename_image, verbose_name='image'),
        ),
    ]
