# Generated by Django 5.2.8 on 2025-11-17 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_absuser_fio_alter_request_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 17, 11, 42, 34, 610345), help_text="date and time of design's creation", verbose_name='creation date'),
        ),
    ]
