# Generated by Django 5.2.8 on 2025-11-18 06:06

import datetime
import requests.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_author_alter_request_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 18, 13, 6, 36, 465278), help_text='Дата и время создания заявки', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение дизайна', upload_to=requests.utilities.rename_image, verbose_name='Изображение'),
        ),
    ]
