# Generated by Django 5.2.8 on 2025-11-19 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_creation_date_alter_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 19, 8, 39, 38, 594794), help_text='Дата и время создания заявки', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('n', 'Новая'), ('a', 'Принята в работу'), ('c', 'Выполнено')], default='n', help_text='request status', max_length=1),
        ),
    ]
