# Generated by Django 5.2.8 on 2025-11-19 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_alter_request_options_alter_request_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 19, 9, 34, 45, 368626), help_text='Дата и время создания заявки', verbose_name='Дата создания'),
        ),
    ]
