# Generated by Django 5.2.8 on 2025-11-19 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_request_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 9, 56, 58, 249484), help_text='Дата и время создания заявки', verbose_name='Дата создания'),
        ),
    ]
