# Generated by Django 5.2.8 on 2025-11-19 04:36

import datetime
import requests.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_request_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed_image',
            field=models.ImageField(blank=True, help_text='Добавочное изображение выполненного дизайна', null=True, upload_to=requests.utilities.rename_image, verbose_name='Изображение выполненного дизайна'),
        ),
        migrations.AlterField(
            model_name='request',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 11, 36, 41, 242327), help_text='Дата и время создания заявки', verbose_name='Дата создания'),
        ),
    ]
